apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: vova-nodejs-docker-webapp
  labels:
    app: vova-nodejs-docker-webapp

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: vova-nodejs-docker-webapp

  template:
    metadata:
      labels:
        app: vova-nodejs-docker-webapp
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/vova-nodejs-docker-webapp:master
          name: vova-nodejs-docker-webapp
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        cloud.google.com/gke-nodepool: workshop-pool
